# -*- coding: utf-8 -*-
"""[PYTHON] PROJECT MOVIES TICKETS - Thuy Linh Nguyen

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H5gk1P-8wfCGGwXF77L5GNXdW7BOCS39

#**1. Load Data**
"""

#Import library
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

#Dimension Tables
df_customer=pd.read_csv('/content/drive/MyDrive/Data for Python Maz/movie_ticket_data/movie_ticket_data/customer.csv')
df_campaign=pd.read_csv('/content/drive/MyDrive/Data for Python Maz/movie_ticket_data/movie_ticket_data/campaign.csv')
df_device=pd.read_csv('/content/drive/MyDrive/Data for Python Maz/movie_ticket_data/movie_ticket_data/device_detail.csv')
df_status=pd.read_csv('/content/drive/MyDrive/Data for Python Maz/movie_ticket_data/movie_ticket_data/status_detail.csv')
#Fact Table
df_ticket=pd.read_csv('/content/drive/MyDrive/Data for Python Maz/movie_ticket_data/movie_ticket_data/ticket_history.csv')

"""# **2. Data Cleaning**

## **2.1 Check Data Type, value NULL & Duplicates**

#### Table: df_customer
"""

df_customer.info()

"""Notes:
- 131.400 rows & 3 collumns
- No NULL values in any of the columns
- Data type check → The dob column has an incorrect type → Convert from object to datetime
"""

df_customer['dob']=pd.to_datetime(df_customer['dob'])
df_customer.info()

"""#### Table: df_device"""

df_device.head(2)

df_device.info()

"""Notes:
- 139.902 cols & 3 rows
- The datatype of all columns are appropriate
- The 'device_number' and 'model' cols contain NULL values -> Check the NULL ratio in these cols (If the ratio is very small- they can be removed; otherwise, replace with another words like 'unknow' or 'undefined')

"""

#Create function to cal the NULL ratio
def calc_null_rate(df):
  newdf=df.isnull().sum().to_frame('null_count')
  newdf[['null_rate']]=newdf[['null_count']]/len(df)
  return newdf.sort_values(by=['null_rate'],ascending=False)

calc_null_rate(df_device)

"""Notes:
+ The NULL ratio in 'device_number' is very low (0.000007) -> Remove rows where 'device_number' is NULL
+ The NULL ratio in 'model' is not too low or too high (0.051029) -> Replace to "unknow"

"""

df_device = df_device.fillna({'model':'unknown'})
df_device = df_device[df_device['device_number'].notna()]

"""#### Table: Status

Notes: Transactions with a successful status (Order successful) have status_id = 1
"""

df_status.info()

"""Notes:
- The 'error_group' col has 1 NULL value (as successful transactions have no errors)
- Replace the NULL value in this column with 'unknown'

#### Table: Campaign
"""

df_campaign.info()

df_campaign['campaign_type'].unique()

"""#### Table: Ticket"""

df_ticket.info()

#Convert the datatype of 'time' col
df_ticket['time']=pd.to_datetime(df_ticket['time'])

#Remove duplicated values
df_ticket.drop_duplicates(inplace=True)

"""## **2.2 Join Tables**"""

df_join_customer=pd.merge(df_ticket,df_customer,how='left',on='customer_id')

df_join_status=pd.merge(df_join_customer,df_status,how='left',on='status_id')

df_join_campaign=pd.merge(df_join_status,df_campaign,how='left',on='campaign_id')

df_join_all=pd.merge(df_join_campaign,df_device,how='left', on='device_number')

df_join_all.head(2)

df_join_all.info()

#Check the NULL ratio in the table
calc_null_rate(df_join_all)

"""### Notes:
After joining tables, some columns still have NULLs:
- 'error_group': NULLs are expected for successful transactions → Replace with 'unknown'.
- 'campaign_type': NULLs appear only for non-promotional orders → Replace with 'unknown'.
- 'platform & model': NULLs may occur if device_id is missing → Replace with 'unknown'.
"""

#Repalce NULL values
df_join_all=df_join_all.fillna({'platform':'unknown','model':'unknown','error_group':'unknown','campaign_type':'unknown'})

"""## **2.3 View all values of each collumns**"""

df_join_all.nunique().sort_values(ascending=False)

# List all the values in all cols
specific_cols=['movie_name','description','paying_method','campaign_type','usergender','platform', 'error_group']
for col in specific_cols:
  print(col + ':', np.sort(df_join_all[col].unique().astype(str)))
  print('\r')
  print('--------------------------------------------------')
  print('\r')

"""# **3. Analyze**

## **3.1 Customer portrait**

### **Age and Gender Distribution**
"""

#Print the current date
from datetime import datetime
current_day=datetime.now()
current_day

#Print the age of customers
col_days = (current_day - df_join_all['dob']).dt.days
df_join_all['age']=col_days/365.25 #Tính cả năm nhuận
df_join_all['age'].astype(int)

df_cus = df_join_all[['customer_id','usergender','age']]
df_cus['age']=df_cus['age'].astype(int)

#Remove duplicates in the col 'customer_id'
df_cus.drop_duplicates(inplace=True)

#View the Age Distribution
plt.figure(figsize=(8,4))
df_cus['age'].hist(bins=30,color='cornflowerblue',grid=False)

plt.title('Age distribution')
plt.xlabel('Age')
plt.ylabel('Number of Customers')
plt.show()

#View some popular age
df_cus_top_age = df_cus[df_cus['usergender']!='Not verify'].groupby('age').agg(total_customers=('customer_id','count')).sort_values(by='total_customers',ascending=False).reset_index()
df_cus_top_age.head(10)

df_cus_top_age = df_cus[df_cus['usergender']!='Not verify'].groupby('age').agg(total_customers=('customer_id','count')).sort_values(by='age',ascending=False).reset_index()
df_cus_top_age.head(10)

"""Notes:
- Most customers are aged between 25-35.
- The peak of the histogram falls within 30-35, indicating the highest number of customers in this age range.
- Some anomalies exist, such as an unusual increase in the 55-60 age group.
- There are customers over 100 years old placing orders (requires verification).
"""

#Age Distribution by Gender

plt.figure(figsize=(8,4))

male_age= df_cus[df_cus['usergender']=='Male']['age']
female_age=df_cus[df_cus['usergender']=='Female']['age']
unknown_age=df_cus[df_cus['usergender']=='Not verify']['age']

plt.hist(male_age, bins=30, alpha=0.3, color='cornflowerblue', label='Male')
plt.hist(female_age, bins=30, alpha = 0.3, color = 'salmon', label = 'Female')
plt.hist(unknown_age, bins=30, alpha = 0.3, color = 'limegreen', label = 'Not verify')

plt.title('Age Distribution by Gender')
plt.xlabel('ages')
plt.ylabel('Number of customers')
plt.legend()
plt.show()

"""Notes: There is a coincidence where the Gender Verify group (lime green) is concentrated around the age of 55

> Question: Could it be that users in this age range have not verified their accounts (which is why their gender is unknown, while their DOB might be defaulted to 1970)?

### **Check 'Not Verify'**
"""

df_gender= df_cus.groupby('usergender').agg(total_cus=('customer_id','count')).reset_index()
df_gender

#The proportion of 3 genders
plt.figure(figsize=(8,4))

plt.pie(df_gender['total_cus'],
        labels=df_gender['usergender'],
        colors=['cornflowerblue','lightsteelblue','slategrey'],
        autopct='%1.0f%%',
        startangle=90)

plt.title('Gender Proportion')
plt.show()

"""Notes:The 'Not verify' group accounts for 11% -> 2 possible cases:
- If they manually entered their DOB, the age data is accurate
- If they did not enter it, the system might auto-fill it as 1970 (~55 years old)
(This is just a hypothesis, as many apps default to this when DOB is missing, potentially causing outliers in the age data)

> Next step: Verify this by checking the exact age distribution within the unverified group.
"""

df_cus_check=df_cus[df_cus['usergender']=='Not verify'].groupby('age').agg(number=('customer_id','count')).reset_index().sort_values(by='number',ascending=False)
df_cus_check.head(5)

"""Notes: The increase in the "Verify" group aligns with the 55-year-old range (born in 1970)
> These customers likely didn't enter DOB (auto-filled as 1970) or manually entered 1970

### **Age generation distribution**

Notes: We can analyze the age by dividing 4 groups
"""

df_cus_3 = df_join_all.drop_duplicates(subset=['customer_id'])[['customer_id','dob','usergender','age']]
df_cus_3['age']=df_cus_3['age'].astype(int)
df_cus_3.head(5)

"""#### **Content of Age Distribution:**
> We choose the current year is 2025
+ Baby Boomers (1946 - 1964): 61-79
+ Generation X (1965 - 1980):45- 60
+ Generation Y (Millennials) (1981 - 1996): 29-44
+ Generation Z (1997 - 2012): 16-28

Notes: In this section, although some customers are older than the Baby Boomers group, they have been included for analysis along with this generation
"""

df_cus_3['age_generation'] = df_cus_3['dob'].apply(lambda x: 'Baby Bommers' if x.year < 1965
                                                     else 'Gen X' if x.year < 1981
                                                     else 'Gen Y' if x.year < 1997
                                                     else 'Gen Z' if x.year < 2013 else 'Others')
df_cus_3.head(4)

df_cus_4= df_cus_3[df_cus_3['usergender']!='Not verify'].groupby('age_generation').agg(total_cus = ('customer_id','count')).sort_values(by='total_cus',ascending=False).reset_index()
df_cus_4.head(5)

df_cus_4['total']=df_cus_4['total_cus'].sum()
df_cus_4

df_cus_4['percent_gen']=((df_cus_4['total_cus']/df_cus_4['total'])*100).round(2)
df_cus_4

df_others_gen = df_cus_3[df_cus_3['age_generation']=='Others'][['customer_id','dob','age']].sort_values(by='age',ascending=False)
df_others_gen.head(5)

"""#### Notes:
- 1 customer has a negative age (-10) → Verify.
- Gen Alpha (2013 to present) makes up 0.12%
> Update table (remove -10, add Alpha group)
"""

df_cus_3 = df_cus_3[df_cus_3['age']>0]
df_cus_3['age_generation'] = df_cus_3['dob'].apply(lambda x: 'Baby Bommers' if x.year < 1965
                                                     else 'Gen X' if x.year < 1981
                                                     else 'Gen Y' if x.year < 1997
                                                     else 'Gen Z' if x.year < 2010
                                                     else 'Gen Alpha')
df_cus_3.head(4)

df_cus_4= df_cus_3[df_cus_3['usergender']!='Not verify'].groupby('age_generation').agg(total_cus = ('customer_id','count')).sort_values(by='total_cus',ascending=False).reset_index()
df_cus_4.head(5)

"""Notes: Gen Z has the highest number of customers

#### **Combined view of 2 charts**
"""

plt.figure(figsize=(13,4))

ax1 = plt.subplot(1,2,1)
df_cus_3[df_cus_3['usergender']!= 'Not verify']['age'].hist(bins=30,color='cornflowerblue',grid=False)
plt.title('Age distribution')
plt.xlabel('Age')
plt.ylabel('Number of Customers')
ax2 = plt.subplot(1,2,2)
plt.pie(df_cus_4['total_cus'],
        labels=None,
        colors=['cornflowerblue','lightsteelblue','slategrey'],
        autopct='%1.1f%%',
        startangle=90,
        labeldistance=1.1)
plt.legend(df_cus_4['age_generation'],loc="upper left", bbox_to_anchor=(1, 1))
plt.title('Age generation distribution')

plt.show()

"""Notes: After removing the 'Not verify' user gender group, the Age distribution no longer has outliers

## **3.2 Time Series Data - When did customers buy tickets**
"""

#Add some new cols related time: weekly, monthly, yearly or month-year
df_join_all['Month']=df_join_all['time'].dt.month
df_join_all['Hour']=df_join_all['time'].dt.hour
df_join_all['Day Name']=df_join_all['time'].dt.day_name()
df_join_all['year_month']=df_join_all['time'].dt.strftime('%Y-%m')

"""#### **The number of tickers by Month Year**"""

#Month Year
df_month_year = df_join_all.groupby('year_month').agg(no_of_tickets=('ticket_id','count')).sort_values(by='year_month').reset_index()
df_month_year.head(4)

plt.figure(figsize=(8,4))

plt.fill_between(df_month_year['year_month'],
                 df_month_year['no_of_tickets'],
                 color='cornflowerblue',
                 alpha=0.7)

plt.title('Number of Tickets by Year-Month')
plt.xlabel('Year-Month')
plt.ylabel('Number of Tickets')
plt.xticks(rotation=90)
plt.show()

"""**Notes:**
- Some time periods are missing from the display.
> Create a time dimension table and join it with the data to check if the issue is due to errors or missing data for these months (4/2020, 8/2021, 9/2021).

#### **A TIME DIMENSION TABLE**
"""

start_date = '2019-01-01'
end_date = '2022-12-31'

date_range = pd.date_range(start=start_date, end=end_date,freq='MS')

list_month = date_range.month
list_month_name = date_range.strftime('%B')
list_year = date_range.year
list_year_month = date_range.strftime('%Y-%m')

dim_time = pd.DataFrame({
    'month_number': list_month,
    'month_name': list_month_name,
    'year': list_year,
    'year_month': list_year_month
})
dim_time.head(4)

# Merge 2 tables to fill in the missing data
df_time_merge = pd.merge(dim_time,df_month_year,how='left',on='year_month')
df_time_merge.head(4)

plt.figure(figsize=(8,4))

plt.fill_between(df_time_merge['year_month'],
                 df_time_merge['no_of_tickets'],
                 color='cornflowerblue',
                 alpha=0.7)

plt.title('Number of Tickets by Month')
plt.xlabel('Year-Month')
plt.ylabel('Number of Tickets')
plt.xticks(rotation=90)
plt.show()

"""Notes: At this point, the missing values (NaN sections in the chart) are blank

#### **The number of Tickets by Day Name**
"""

df_day_name = df_join_all.groupby('Day Name').agg(no_of_tickets=('ticket_id','count')).sort_values(by='Day Name').reset_index()
df_day_name

df_join_all['Dayofweek']=df_join_all['time'].dt.dayofweek
df_join_all.head(2)

df_day_name_1 = df_join_all.groupby(['Dayofweek','Day Name']).agg(no_of_tickets=('ticket_id','count')).sort_values(by='Dayofweek').reset_index()
df_day_name_1.head(4)

plt.figure(figsize=(8,4))

plt.fill_between(df_day_name_1['Day Name'],
                 df_day_name_1['no_of_tickets'],
                 color='cornflowerblue',
                 alpha=0.7)

plt.title('Number of Tickets by Day Name')
plt.xlabel('Day Name')
plt.ylabel('Number of Tickets')
plt.xticks(rotation=90)
plt.show()

"""#### **The number of tickets Hour**"""

df_hour = df_join_all.groupby('Hour').agg(no_of_tickets=('ticket_id','count')).sort_values(by='Hour').reset_index()
df_hour.head(4)

plt.figure(figsize=(8,4))
plt.fill_between(df_hour['Hour'],df_hour['no_of_tickets'],color='cornflowerblue',alpha=0.7)

x_values = [i for i in range(24)]

plt.title('Number of Tickets by Hour')
plt.xlabel('Hour')
plt.ylabel('Number of Tickets')
plt.xticks(x_values)
plt.show()

"""**Notes:**
- In the early hours (0 AM - 7 AM), ticket sales are low, ranging from 0 to 2,000
- From 7 AM - 12 PM, sales increase and then start declining after 7 PM
- Peak ticket sales occur between 11 AM - 1 PM and 6 PM - 8 PM

## **3.3 Factors Analysis**

### **Payment Platform**
"""

df_platform_0 = df_join_all.groupby('platform').agg(no_of_tickets=('ticket_id','count')).reset_index()
df_platform_0

calc_null_rate(df_platform_0)

"""Notes: 'Unknown' devices are few (78) -> they can be removed to compare payment trends between mobile and website"""

df_platform = df_join_all[df_join_all['platform'] != 'unknown'].groupby('platform').agg(no_of_tickets=('ticket_id','count')).reset_index()
df_platform

plt.figure(figsize=(8,4))

plt.barh(
    df_platform['platform'],
    df_platform['no_of_tickets'],
    color = df_platform['platform'].replace({'mobile':'lightskyblue','website':'tomato'})
)

plt.title('Number of Tickets by Platforms')
plt.ylabel('Platforms')
plt.xlabel('Number of Tickets')

for index, value in enumerate(df_platform['no_of_tickets']):
  plt.text(value, index, str(value))

plt.figure(figsize=(13,4))

plt.pie(
    df_platform['no_of_tickets'],
    labels = df_platform['platform'],
    colors=df_platform['platform'].replace({'mobile':'lightskyblue','website':'tomato'}),
    autopct = '%1.0f%%',
    startangle=90
)

plt.show()

# Create a time-based table to analyze platform usage trends over time
df_platform_1 = df_join_all.groupby(['year_month','platform']).agg(
    no_of_tickets=('ticket_id','count')
).reset_index()
df_platform_1

df_platform_1 = df_platform_1[df_platform_1['platform'] != 'unknown']
df_platform_1

plt.figure(figsize=(8,4))

#Data
df_mobile_line = df_platform_1[df_platform_1['platform']=='mobile']
df_website_line = df_platform_1[df_platform_1['platform']=='website']

#Line 1:
plt.plot(df_mobile_line['year_month'],
         df_mobile_line['no_of_tickets'],
         label = 'mobile',
         marker = 'o',
         markersize = 4,
         color = 'tomato',
         linewidth = 2,
)

#Line 2:
plt.plot(df_website_line['year_month'],
         df_website_line['no_of_tickets'],
         label = 'website',
         marker = 'o',
         markersize = 4,
         color = 'lightskyblue',
         linewidth = 2,
)

plt.title('Trendline of Platforms')
plt.xticks(rotation=90)
plt.legend()

plt.show()

# Website start being used:
df_website_line.sort_values(by='year_month').head(5)

"""Notes: The website started being used in January 2020, with more data appearing in September 2020

### **Operating System version**
"""

df_join_all['model'].unique()

"""> Operating System version has 4 groups
+ IOS (Some model has the word 'iPhone')
+ Android others (has 'Samsung','Oppo',...)
+ Browser (browser)
+ Unknown
"""

df= df_join_all.groupby('model').agg(no_of_tickets=('ticket_id','count')).sort_values(by='no_of_tickets',ascending=False).reset_index()

df

#Add col 'os_version'
df_join_all['os_version'] = df_join_all['model'].apply(lambda x:'ios'
                                       if ('iPhone' in x or 'iPod' in x or 'iPad' in x)
                                       else 'browser' if x=='browser'
                                       else 'unknown' if x=='unknown'
                                       else 'android & others')

df_join_all.head(4)

df_model_1 = df_join_all.groupby('os_version').agg(no_of_tickets=('ticket_id','count')).reset_index()
df_model_1

"""**100% stacked area chart**


"""

df_model_4 = (
    df_join_all
    .pivot_table(index='year_month', columns='os_version', aggfunc='count',values='ticket_id')
    .reset_index()

)
df_model_4.head(4)

"""#### **Combined view of 3 charts**"""

plt.figure(figsize=(12,8))

#Plot 1
axis1 = plt.subplot(2,2,1)
plt.barh(
    df_model_1['os_version'], df_model_1['no_of_tickets'],
    color = df_model_1['os_version'].replace({'browser': 'lightsteelblue',  'android & others': 'lightskyblue', 'ios': 'cornflowerblue', 'unknown': 'steelblue'})
)

plt.title('Number of Tickets by OS Versions')
plt.ylabel('OS Versions')
plt.xlabel('Number of Tickets')

for index, value in enumerate(df_model_1['no_of_tickets']):
  plt.text(value, index, str(value))

#Plot 2
axis2 = plt.subplot(2,2,2)
plt.pie(
    df_model_1['no_of_tickets'],
    labels = df_model_1['os_version'],
    colors=df_model_1['os_version'].replace({'browser': 'lightsteelblue',  'android & others': 'lightskyblue', 'ios': 'cornflowerblue', 'unknown': 'steelblue'}),
    autopct = '%1.0f%%',
    startangle=90
)
plt.title('Os versions Portition')

#Plot 3
axis3 = plt.subplot(2,1,2)
plt.fill_between(df_model_4['year_month'], df_model_4['ios'],color='cornflowerblue',alpha=0.5, label='ios')
plt.fill_between(df_model_4['year_month'], df_model_4['android & others'],color='lightskyblue',alpha=0.5, label='android & others')
plt.fill_between(df_model_4['year_month'], df_model_4['browser'],color='lightsteelblue',alpha=0.5, label='browser')
plt.fill_between(df_model_4['year_month'], df_model_4['unknown'],color='steelblue',alpha=0.5, label='unknown')


plt.title('Number of Tickets of OS version by time')
plt.ylabel('Number of Tickets')
plt.xlabel('year_month')
plt.xticks(rotation=90)
plt.legend()
plt.show()

plt.subplots_adjust(hspace=3, top=0.8)

"""### **Paying Method**

"""

df_payment_0 = df_join_all[df_join_all['paying_method'] != 'other']

df_payment_1 = df_payment_0.groupby('paying_method').agg(no_of_orders=('ticket_id','count')).sort_values(by='no_of_orders').reset_index()
df_payment_1

#Pivot table
df_payment_2 = (df_payment_0
                .pivot_table(index='year_month',columns='paying_method',aggfunc='count',values='ticket_id')
                .reset_index())
df_payment_2.head(4)

"""### **Vẽ biểu đồ miền dạng 100%**"""

#Tạo bảng dạng %
df_payment_3 = df_payment_2.fillna(0)
df_payment_3['total'] = df_payment_2.iloc[:,1:].sum(axis=1)

#Tính %
for i in df_payment_3.columns[1:5]:
  df_payment_3[i+'_pct']= df_payment_3[i]/df_payment_3['total']
df_payment_3.head(5)

"""#### **Combined view of 4 charts**"""

plt.figure(figsize= (12,8))

#Plot 1
axis1=plt.subplot(3,2,1)
plt.barh(df_payment_1['paying_method'],
         df_payment_1['no_of_orders'],
         color=df_payment_1['paying_method'].replace({ 'bank account': 'lightsteelblue',  'credit card': 'lightskyblue', 'debit card': 'cornflowerblue', 'money in app': 'steelblue'})
)

plt.title('Number of Tickets by Payment Method')
plt.ylabel('Payment Method')
plt.xlabel('Number of Tickets')

for index, value in enumerate(df_payment_1['no_of_orders']):
  plt.text(value, index, str(value))

#Plot 2
axis2 = plt.subplot(3,2,2)
plt.pie(df_payment_1['no_of_orders'],
        labels=df_payment_1['paying_method'],
        colors=df_payment_1['paying_method'].replace({ 'bank account': 'lightsteelblue',  'credit card': 'lightskyblue', 'debit card': 'cornflowerblue', 'money in app': 'steelblue'}),
        autopct = '%1.0f%%',
    startangle=90)

plt.title('Percent of Payment Method')

#Plot 3
axis3= plt.subplot(3,1,2)
plt.fill_between(df_payment_2['year_month'],df_payment_2['bank account'],color='lightsteelblue',alpha=0.5, label='bank account')
plt.fill_between(df_payment_2['year_month'],df_payment_2['credit card'],color='lightskyblue',alpha=0.5, label='credit card')
plt.fill_between(df_payment_2['year_month'],df_payment_2['debit card'],color='cornflowerblue',alpha=0.5, label='debit card')
plt.fill_between(df_payment_2['year_month'],df_payment_2['money in app'],color='steelblue',alpha=0.5, label='money in app')

plt.title('Number of Tickets of Payment Method by time')
plt.ylabel('Number of Tickets')
plt.xlabel('year_month')
plt.xticks(rotation=90)
plt.legend()

#Plot 4
axis4=plt.subplot(3,1,3)
plt.stackplot(df_payment_3['year_month'],
              df_payment_3['bank account_pct'],
              df_payment_3['credit card_pct'],
              df_payment_3['debit card_pct'],
              df_payment_3['money in app_pct'],
              labels = ['bank account','credit card',	'debit card',	'money in app'],
              colors=['cornflowerblue','lightsteelblue','slategrey','royalblue'],
              alpha=0.7
)
plt.title('Number of tickets of method by time')
plt.ylabel('No of Tickets')
plt.legend(loc='upper right', bbox_to_anchor=(1.15, 1))
plt.xticks(rotation=90)

plt.subplots_adjust(hspace = 1.0, top = 0.9)
plt.show()

"""### **Promotion**"""

df_join_all.rename(columns={'campaign_type':'type'},inplace=True)

df_join_all[['campaign_id','type']]

df_join_all['type'].value_counts()

"""Notes: Analyze campaign promotions by comparing revenue from Promotion vs. Non-Promotion groups
- Promotion: Direct discount, voucher, reward points
- Non-Promotion: Unknown
"""

df_join_all['campaign_type'] = df_join_all['type'].apply(lambda x: 'Non-Promotion' if x=='unknown' else 'Promotion')
df_join_all. head(2)

df_promotion_1 = df_join_all.groupby(['year_month','campaign_type']).agg(no_of_tickets=('ticket_id','count')).sort_values(by='year_month').reset_index()
df_promotion_1.head(5)

df_promotion_1['year_month'] = pd.to_datetime(df_promotion_1['year_month'], format='%Y-%m')

df_promotion_2 = df_join_all.groupby('campaign_type').agg(no_of_tickets=('ticket_id','count')).sort_values(by='no_of_tickets').reset_index()
df_promotion_2

#Pivot table
df_promotion_3 =  df_promotion_1.pivot_table(index='year_month',columns='campaign_type',values='no_of_tickets').reset_index()
df_promotion_3.head(5)

df_promotion_4 = df_promotion_3.fillna(0)
df_promotion_4['total'] = df_promotion_3.iloc[:,1:].sum(axis=1)

for i in df_promotion_4.columns[1:3]:
  df_promotion_4[i+'_pct']= df_promotion_4[i]/df_promotion_4['total']
df_promotion_4.head(5)

"""#### **Combined view of 4 charts**"""

plt.figure(figsize=(12,8))
#Bar Chart
ax1=plt.subplot(3,2,1)
plt.barh(df_promotion_2['campaign_type'],
         df_promotion_2['no_of_tickets'],
         color=df_promotion_2['campaign_type'].replace({'Promotion':'lightskyblue','Non-Promotion':'tomato'}))

plt.title('Number of Tickets by Campaigns')
plt.ylabel('Campaigns')
plt.xlabel('Number of Tickets')


for index, value in enumerate(df_promotion_2['no_of_tickets']):
  plt.text(value, index, str(value))

#Pie chart
ax2=plt.subplot(3,2,2)
plt.pie(df_promotion_2['no_of_tickets'],
        labels=df_promotion_2['campaign_type'],
        autopct='%1.0f%%',
         startangle=90,
        colors=df_promotion_2['campaign_type'].replace({'Promotion':'lightskyblue','Non-Promotion':'tomato'}))

plt.title('Percent of Campaigns')
plt.legend(bbox_to_anchor=(1, 1))

#Line chart
ax3=plt.subplot(3,1,2)

df_pro = df_promotion_1[df_promotion_1['campaign_type']=='Promotion']
df_non_pro = df_promotion_1[df_promotion_1['campaign_type']=='Non-Promotion']

plt.plot(df_pro['year_month'],
         df_pro['no_of_tickets'],
         label = 'Promotion',
         marker = 'o',
         markersize =4,
         color='lightskyblue',
         linewidth=1.5)

plt.plot(df_non_pro['year_month'],
         df_non_pro['no_of_tickets'],
         label = 'Non-Promotion',
         marker = 'o',
         markersize =4,
         color='tomato',
         linewidth=1.5)

plt.title('Number of Tickets using Campaigns')
plt.xlabel('Year Month')
plt.ylabel('Campaigns')
plt.legend()

x_values = pd.date_range(start='2019-01', end='2022-12', freq='M').strftime('%Y-%m').tolist()
plt.xticks(x_values, rotation=90)

#100% stacked area chart
ax4=plt.subplot(3,1,3)
plt.stackplot(df_promotion_4['year_month'],
              df_promotion_4['Non-Promotion_pct'],
              df_promotion_4['Promotion_pct'],
              labels = ['Non-Promotion','Promotion'],
              colors=['tomato','lightskyblue'],
              alpha=0.7
)
plt.title('Number of tickets of Campaigns by time')
plt.ylabel('No of Tickets')
plt.legend(loc='upper right', bbox_to_anchor=(1.15, 1))

x_values = pd.date_range(start='2019-01', end='2022-12', freq='M').strftime('%Y-%m').tolist()
plt.xticks(x_values, rotation=90)

#Show
plt.subplots_adjust(hspace = 1.5, top = 0.9)
plt.show()

"""### **Which movies they watched ?**"""

df_movie_1 = df_join_all[df_join_all['status_id']==1].groupby('movie_name').agg(no_of_tickets=('ticket_id','count'),
                                                   total_cus=('customer_id','nunique'), #Vì 1 khách hàng có thể mua nhiều vé
                                                   total_revenue=('final_price','sum')).sort_values(by='no_of_tickets',ascending=False).reset_index()
df_movie_1.head(5)

"""Notes: Due to the large number of movies, the analysis below focuses only on films with ticket sales over 1,000"""

#List the name of 100 movies
list_movie_name = df_movie_1[df_movie_1['no_of_tickets']>=1000]['movie_name'].unique()
selected_list_movie=list(list_movie_name)
selected_list_movie

df_movie_2 = df_join_all[(df_join_all['status_id']==1) & df_join_all['movie_name'].isin(selected_list_movie)].groupby(['year_month','movie_name']).agg(no_of_tickets=('ticket_id','count')).reset_index()
df_movie_2.head(4)

#Pivot Table
df_movie_3 = df_movie_2.pivot_table(index='year_month',columns='movie_name',values='no_of_tickets').reset_index()
df_movie_3.head(5)

ax = df_movie_3.plot(x='year_month', kind='bar',stacked='True',figsize=(15,6),width=0.8, alpha=0.7)

ax.set_title('Movie Name Trend')
ax.set_ylabel('Number of Tickets')

plt.legend(title='Movies', loc='upper right', bbox_to_anchor=(1.35, 1))

plt.show()

#TOP 5 movies with the highest ticket sales
df_movie_2.sort_values(by='no_of_tickets', ascending=False).head(5)

df_join_all['year'] = pd.to_datetime(df_join_all['time']).dt.year

# Top 2 highest-grossing movies each year
top_movies_each_year = df_join_all.groupby('year').apply(lambda x: x.nlargest(2, 'final_price')).reset_index(drop=True)

top_movies_each_year[['ticket_id','year','year_month','movie_name','final_price']]

"""## **3.4. Customer value dimension**

> **Objective: Analyze the value metrics a customer brings**
>> + **Frequency:** count, day, month
>> + **Monetary:** total_money, total_discount
>> + **Success rate** = number_success/total_success
>> + **Discount_rate** = sum_discount/sum_money
"""

#Run the dataset across all columns
pd.set_option('display.max_colwidth',None)
pd.set_option('display.max_columns',None)
df_join_all.head(4)

#Add the col 'Date' df_join_all
df_join_all['Date']=df_join_all['time'].dt.strftime('%Y-%m-%d')

# create Table 1 for Successful Customers (status_id=1)
# add a function to calculate successful transactions
def cal_n_promotion(x):
  return(x=='Promotion').sum()

df_success_metric = df_join_all[df_join_all['status_id']==1].groupby('customer_id').agg(n_success=('ticket_id','count'),
                                                  no_of_months=('year_month','nunique'),
                                                  total_money=('original_price','sum'),
                                                  total_discount=('discount_value','sum'),
                                                  total_promotion=('campaign_type',cal_n_promotion),
                                                  no_of_days=('Date','nunique')).reset_index()
df_success_metric.head(5)

calc_null_rate(df_success_metric)

#Create table 2 for failed payment customers

def cal_no_success(x):
  return(x!=1).sum()

df_failed_metric = df_join_all.groupby('customer_id').agg(no_of_tickets=('ticket_id','count'),
                                                           n_failed=('status_id',cal_no_success)).reset_index()

df_failed_metric.head(5)

#Mergetable 1 and table 2
df_value_1 = pd.merge(df_failed_metric, df_success_metric,how='left',on='customer_id').fillna(0)
df_value_1.head(5)

#Cal other metrics
df_value_1['success_rate']=df_value_1['n_success']/df_value_1['no_of_tickets']
df_value_1['promotion_rate']=df_value_1['total_promotion']/df_value_1['n_success']
df_value_1['discount_rate']=df_value_1['total_discount']/df_value_1['total_money']
df_value_1.head(5)

df_value_1.iloc[:,1:].hist(figsize=(12,9),grid=False,color='cornflowerblue', bins=20)
plt.show()

"""**Notes:**
- Most customers buy only 1-2 tickets, but a few buy a lot → Check these users
- Success Rate: ~10% of transactions have a Success Rate = 0% → Possible issue?
- Promotion Rate: 6,000+ customers only used promotions (rate = 100%)
- 6,000 customers used promotions only once—any link to the 100% promotion rate group?

### **Frequency & anomaly behavior**
"""

df_value_1['customers_dis'] = df_value_1['n_success'].apply(lambda x:'more than 10' if x>=10
                                                                 else str(x))

# How many customers correspond to each ticket quantity?
df_value_2 = df_value_1.groupby('customers_dis').agg(no_of_customers=('customer_id','count')).reset_index()
df_value_2

"""Notes: Vì số lượng khách mua số lượng vé lớn cỡ từ 1-3 người => Gộp luôn vào nhóm (more than 10: mua nhiều hơn 10 vé)"""

plt.figure(figsize=(8,4))

plt.barh(df_value_2['customers_dis'],
         df_value_2['no_of_customers'],
         color='cornflowerblue')

plt.title('Number of Customets of each group ticket')
plt.ylabel('Group tickets')
plt.xlabel('Number of Customers')

for index, value in enumerate(df_value_2['no_of_customers']):
  plt.text(value, index, str(value))

df_value_1.count()

"""Notes: Out of 119,477 customers:
- 87,921 customers bought only 1 ticket (73.58%)
- 13.4% purchased 2-3 tickets
- A small group bought a high number of tickets → needs further analysis:
> - Bulk purchase at once → Possible hoarding ?
> - Spread over time → Normal behavior
"""

df_value_3 = df_value_1.groupby('n_success').agg(no_of_customers=('customer_id','count')).sort_values(by='n_success',ascending=False).reset_index()

"""Notes:
- 1 customer purchased 260 tickets (highest)
- 4 customers bought 100-110 tickets
"""

df_value_4 = list(df_value_1[df_value_1['n_success']>30]['customer_id'].unique())

df_value_5 = df_join_all[(df_join_all['status_id']==1) & df_join_all['customer_id'].isin(df_value_4)].groupby(['year_month','customer_id']).agg(no_of_tickets=('ticket_id','count')).reset_index()

# Pivot table
df_value_6 = df_value_5.pivot_table(index='year_month',columns='customer_id',values='no_of_tickets').reset_index()

ax = df_value_6.plot(x='year_month', kind='bar',stacked='True',figsize=(15,6),width=0.8, alpha=0.7)

ax.set_title('Customer buying Tickets')
ax.set_ylabel('Number of Tickets')

plt.legend(title='Customers', loc='upper right', bbox_to_anchor=(1.15, 1))

plt.show()

"""Notes:
- Customers who bought ≥30 tickets had distributed purchases → No signs of ticket hoarding or resale
- No abnormalities detected

### **Promotion's Campaigns**
"""

df_value_1['promotion_dis'] = df_value_1['total_promotion'].apply(lambda x:'more than 10' if x>=10 else str(x))

df_protype_2 = df_value_1.groupby('promotion_dis').agg(no_of_customers=('customer_id','count')).reset_index()

plt.figure(figsize=(8,4))

plt.barh(df_protype_2['promotion_dis'],
         df_protype_2['no_of_customers'],
         color='cornflowerblue')

plt.title('Number of Customers using Promtion/Non-Promotion')
plt.ylabel('Promotion')
plt.xlabel('Number of Customers')

for index, value in enumerate(df_protype_2['no_of_customers']):
  plt.text(value, index, str(value))

df_value_1['customer_id'].count()

#The percentage of customers who never participated in any promotion is:
50498/119477

#The percentage of customers who participated in at least one promotion is:
(119477-50498)/119477

#The percentage of customers who participated in a promotion only once is:
61334/(119477-50498)

"""Notes:
- ~42% of customers did not participate in any promotions
- ~58% joined at least one promotion
- Among them, 89% used a promotion only once
- Two possible reasons:
> - Customers only purchased once and never returned
> - Promotions were limited to one-time use per customer (targeting new users) → Need to verify with the Product or Marketing team

**Check and analyze the types of promotions customers used**
"""

df_protype_0 = df_join_all[df_join_all['status_id']==1].groupby('type').agg(total=('ticket_id','count')).sort_values(by='total',ascending=False).reset_index()
df_protype_0

plt.figure(figsize=(8, 4))

plt.pie(df_protype_0['total'],
        labels=df_protype_0['type'],
        autopct='%1.0f%%',
        startangle=90,
        colors=['lightblue', 'lightgreen', 'lightcoral', 'lightskyblue']
)

plt.legend(bbox_to_anchor=(1, 1))
plt.show()

"""**Calculate the detailed promotion type ratio for each customer group**"""

df_typepro_3 = df_join_all[(df_join_all['campaign_type']=='Promotion') & df_join_all['status_id']==1].groupby('customer_id').agg(no_of_promotions=('ticket_id','count')).reset_index()

df_typepro_1 = df_join_all[(df_join_all['campaign_type']=='Promotion') & df_join_all['status_id']==1].pivot_table(index='customer_id', columns='type',aggfunc='count',values='ticket_id').reset_index()
df_typepro_1 = df_typepro_1.fillna(0)
df_typepro_1.head(10)

df_typepro_4 = pd.merge(df_typepro_3,df_typepro_1, how='inner', on='customer_id')
df_typepro_4.head(10)

df_typepro_4 = df_typepro_4.drop_duplicates(subset=['customer_id'])

df_typepro_5 = df_typepro_4.groupby('no_of_promotions').agg(no_customers=('customer_id','nunique'),
                                                            no_direct_discount=('direct discount','sum'),
                                                            no_reward_point=('reward point','sum'),
                                                            no_voucher=('voucher','sum')).reset_index()
df_typepro_5.head(12)

#Add the col 'Total'
df_typepro_5['total']=df_typepro_5.iloc[:,2:].sum(axis=1)
df_typepro_5

for i in df_typepro_5.columns[2:5]:
  df_typepro_5[i+'_pct']= df_typepro_5[i]/df_typepro_5['total']

df_typepro_5.head(2)

"""**Create a heatmap for the promotion programs**:"""

format_dict = {'total':'{:.0f}','no_voucher_pct':'{:.0%}','no_direct_discount_pct':'{:.0%}','no_reward_point_pct':'{:.0%}'}

(
    df_typepro_5
    .drop(columns= ['no_direct_discount','no_reward_point','no_voucher'])
    .style
    .format(format_dict)
    .background_gradient(subset=['no_voucher_pct', 'no_reward_point_pct', 'no_direct_discount_pct'], cmap='PuBu')
    .background_gradient(subset=['total'], cmap='YlGn')
)

"""**Notes:**
- ~90% of customers participate in Direct Discount campaigns
- Evaluate customer retention → Do they return? → Measure marketing effectiveness
> If customers use promotions but don’t return, marketing may not be effective, meaning they only join for the one-time discount

## **3.5 Customer Retention - Cohort Analysis**

> + Evaluate customer retention rate
> + Identify key factors affecting retention
>> Analyze Customer Conversion timing based on: First paymnet; First purchase; First app installation
"""

#Import library
from operator import attrgetter
import matplotlib.colors as mcolors
import seaborn as sns

"""Notes: Xem lại data ở trên, thì năm 2020 và 2021 bị thiếu dữ liệu nên sẽ phân tích và so sánh theo 2 năm 2019 và 2022 thôi"""

df_selected_time = df_join_all[(df_join_all['time']>='2022-01-01') & (df_join_all['status_id']==1)]
df_selected_time['first_month'] = df_selected_time.groupby('customer_id')['time'].transform('min').dt.to_period('M')
df_selected_time['current_month'] = df_selected_time['time'].dt.to_period('M')
df_selected_time['subsequent_month']=(df_selected_time['current_month']-df_selected_time['first_month']).apply(attrgetter('n'))

df_cohort = df_selected_time.groupby(['first_month','current_month','subsequent_month']).agg(no_of_customers=('customer_id','nunique')).reset_index()
df_cohort_pivot = df_cohort.pivot_table(index='first_month',columns='subsequent_month',values='no_of_customers')
cohort_size = df_cohort_pivot.iloc[:,0]
retention_matrix = df_cohort_pivot.iloc[:,0:].divide(cohort_size, axis=0)

with sns.axes_style("white"):
    fig, ax = plt.subplots(1, 2, figsize=(12, 8), sharey=True, gridspec_kw={'width_ratios': [1, 11]})

    # retention matrix
    sns.heatmap(retention_matrix,
                mask=retention_matrix.isnull(),
                annot=True,
                fmt='.0%',
                cmap='YlGnBu',
                ax=ax[1])
    ax[1].set_title('Monthly Cohorts: User Retention 2022', fontsize=16)
    ax[1].set(xlabel='subsequent months',
              ylabel='')

    # cohort size
    cohort_size_df = pd.DataFrame(cohort_size).rename(columns={0: 'original customers'})
    white_cmap = mcolors.ListedColormap(['white'])
    sns.heatmap(cohort_size_df,
                annot=True,
                cbar=False,
                fmt='g',
                cmap=white_cmap,
                alpha=0.5,
                ax=ax[0])

    fig.tight_layout()

"""**NOTES:**  
- Retention Rate in 2019 and 2022 remained unchanged as the market was still recovering
- Despite 60-65% of traffic from promotions in 2022, retention remained low

Notes: Analyze whether the Retention Rate differs significantly between Promotion and Non-Promotion groups in 2022
"""

df_year19_cus = df_join_all[(df_join_all['time']>='2022-01-01') & (df_join_all['status_id']==1)].groupby('campaign_type').agg(no_of_customer=('customer_id','nunique')).reset_index()

plt.figure(figsize=(8,4))

plt.pie(df_year19_cus['no_of_customer'],
        labels=df_year19_cus['campaign_type'],
        autopct='%1.0f%%',
        startangle=90,
        colors=('cornflowerblue','tomato')
)

plt.title('Promotion Proportion 2022')
plt.legend()
plt.legend(bbox_to_anchor=(1, 1))

df_year19_ticket = df_join_all[(df_join_all['time']>='2022-01-01') & (df_join_all['status_id']==1)].groupby('campaign_type').agg(no_of_tickets=('ticket_id','nunique')).reset_index()

plt.figure(figsize=(8,4))

plt.pie(df_year19_ticket['no_of_tickets'],
        labels=df_year19_ticket['campaign_type'],
        autopct='%1.0f%%',
        startangle=90,
        colors=('cornflowerblue','tomato')
)
plt.legend()
plt.legend(bbox_to_anchor=(1, 1))

"""**Notes:**

Notes: Differentiate customers based on their first order: Promotion or Organic (Non-Promotion)
- Assign order numbers by customer_id
- If the first order (stt = 1) is a Promotion, classify as Promotion (First_Order)
- To check retention, find customer_id with stt = 2 in the Promotion group (i.e., they returned for a second purchase after using a promotion)
"""

df_data_check = df_join_all[(df_join_all['time']>'2022-01-01') & (df_join_all['status_id']==1)][['customer_id','ticket_id','time','campaign_type']].sort_values(by=['customer_id','time'])

# Assign a sequence number to each customer’s orders
df_data_check['row_number']=df_data_check.groupby('customer_id').cumcount() + 1
df_data_check.head(5)

# Count the number of customers whose first order belongs to the Promotion group
df_data_check[(df_data_check['campaign_type']=='Promotion') & df_data_check['row_number']==1]['customer_id'].nunique()

46397/47505

"""Notes:
- Compared to the Pie chart; 47,505 customers participated in Promotion in 2022, with 46397/47505 (~97%) being first-time participants

> How many of them returned? → Calculate Retention Rate
"""

df_first_promo_list = df_data_check[(df_data_check['campaign_type']=='Promotion') & df_data_check['row_number']==1]['customer_id']
df_first_promo_list.drop_duplicates(inplace=True)

#Merge the two tables to create a dataset containing only customers who used Promotion for the first time
df_first_promo_check = pd.merge(df_data_check,df_first_promo_list, how='inner', on='customer_id')
df_first_promo_check. head(5)

(
    df_first_promo_check[df_first_promo_check['row_number']==2]['customer_id'].nunique()
    /
    df_first_promo_check['customer_id'].nunique()
)

"""Notes: 13.4% of customers returned after their first Promotion purchase
> What about the Organic group?
"""

df_data_check[(df_data_check['campaign_type']=='Non-Promotion') & df_data_check['row_number']==1]['customer_id'].nunique()

list_first_non_promo = df_data_check[(df_data_check['campaign_type']=='Non-Promotion') & df_data_check['row_number']==1]['customer_id']
list_first_non_promo.drop_duplicates(inplace=True)

df_first_non_promo_check = pd.merge(df_data_check,list_first_non_promo, how='inner', on='customer_id')

(
    df_first_non_promo_check[df_first_non_promo_check['row_number']==2]['customer_id'].nunique()
    /
    df_first_non_promo_check['customer_id'].nunique()
)

"""Notes: The first-time Organic customer group has a 13.9% retention rate

## **3.6 Payment success rate**
"""

def cal_success(x):
  return(x==1).sum()

df_sr = df_join_all.groupby('year_month').agg(n_ords=('ticket_id','count'),
                                                   n_success=('status_id',cal_success)).reset_index()
df_sr.head(5)

#Add col: success_rate (=n_success/n_order)

df_sr['success_rate']=(df_sr['n_success']/df_sr['n_ords'])*100
df_sr.head(5)

# a combined chart with a bar chart (number of orders) and a line chart (order success rate)

from matplotlib.ticker import PercentFormatter

fig, ax1 = plt.subplots(figsize=(15,4))

ax1.bar(df_sr['year_month'], df_sr['n_ords'], color="cornflowerblue")
plt.ylabel('#tickets', fontsize=11)
plt.xticks(rotation='vertical')

ax2 = ax1.twinx()
ax2.plot(df_sr['year_month'], df_sr['success_rate'], color="tomato", marker="o", ms=3)
ax2.yaxis.set_major_formatter(PercentFormatter())

plt.ylabel('success rate', fontsize=11)
plt.title('Payment success rate by months', fontsize=14)

"""Notes:
- SR fluctuates between 80-90%; 100% indicates missing data
- High success, but errors persist → Check error groups

"""

def cal_success(x):
  return(x==1).sum()

df_sr_payment = df_join_all[df_join_all['paying_method']!='other'].groupby('paying_method').agg(n_ords=('ticket_id','count'),
                                                   n_success=('status_id',cal_success)).reset_index()

df_sr_payment['success_rate']=(df_sr_payment['n_success']/df_sr_payment['n_ords'])*100
df_sr_payment.sort_values(by='success_rate',ascending=False).head(5)

"""#### **Error Trend**"""

df_error_group = df_join_all[df_join_all['status_id']!=1].groupby(['year_month','error_group']).agg(n_ords=('ticket_id','count')).reset_index()
df_error_group.head(5)

df_error_group['error_group'].unique()

error_color_pairs = [('external','tomato'),('customer','skyblue'),('internal','green')]

plt.figure(figsize=(15,4))
for error, color in error_color_pairs:
  df_err_line = df_error_group[df_error_group['error_group']==error]
  plt.plot(df_err_line['year_month'],
           df_err_line['n_ords'],
           label=error,
           marker='o',
           color=color,
           linewidth=2,
           markersize=2)

plt.title('Total Tickets of error group by months')
plt.xlabel('month')
plt.ylabel('Number of Tickets')
plt.legend(loc='upper right',bbox_to_anchor=(1.15,1))
plt.xticks(rotation=90)
plt.show()

"""Notes:
- Customer errors spread evenly
- Few internal errors
- External errors surged in 2022
"""

df_error = df_join_all[df_join_all['status_id']!=1].groupby(['year_month','description']).agg(n_ords=('ticket_id','count')).sort_values(by='year_month').reset_index()
df_error.head(5)

error_color_pairs = [('Payment failed from bank','gray'),
 ('Insufficient funds in customer account. Please add more funds and try the transaction again.','tomato'),
  ('No response from your bank','skyblue'),
   ('Password locked due to multiple incorrect attempts. Choose Forgot Password to unlock.','green'),
    ('Payment failed from bank','gray'),
     ('Payment overdue','purple'),
      ('Transaction temporarily limited','blue'),
       ('Need verify your account to continue','peru')]

plt.figure(figsize=(15,4))
for error, color in error_color_pairs:
  df_err_line = df_error[df_error['description']==error]
  plt.plot(df_err_line['year_month'],
           df_err_line['n_ords'],
           label=error,
           marker='o',
           color=color,
           linewidth=2,
           markersize=2)

plt.title('Total Tickets of error group by months (Success)')
plt.xlabel('month')
plt.ylabel('Number of Tickets')
plt.legend(loc='upper right',bbox_to_anchor=(1.15,1))
plt.xticks(rotation=90)
plt.show()

"""Notes: Bank errors spiked in 2022 (Payment failed from bank)

#### **Why & How Success_rate = 0%**
"""

list_sr_0 = list(df_value_1[df_value_1['success_rate']<0.1]['customer_id'].unique())

def cal_n_promotion(x):
  return(x=='Promotion').sum()

df_sr_0_metric = (
    df_join_all[df_join_all['customer_id'].isin(list_sr_0)]
    .groupby('customer_id')
    .agg(n_orders = ('ticket_id','count'),
         s_money=('original_price','sum'),
         s_discount=('discount_value','sum'),
         n_promotions=('campaign_type',cal_n_promotion)).reset_index()
)

df_sr_0_metric['promotion_rate'] = df_sr_0_metric['n_promotions']/df_sr_0_metric['n_orders']
df_sr_0_metric['discount_rate'] = df_sr_0_metric['s_discount']/df_sr_0_metric['s_money']

df_sr_0_metric.iloc[:,1:].hist(figsize=(12,9),grid=False,color='cornflowerblue', bins=20)
plt.show()

"""Notes: What error caused them to fail once and stop without retrying?"""

df_error_0 = (
    df_join_all[(df_join_all['status_id']!=1) & (df_join_all['customer_id'].isin(list_sr_0))]
    .groupby(['year_month','description'])
    .agg(n_ords=('ticket_id','count'))
    .sort_values(by ='year_month',ascending=True)
    .reset_index()

  )

error_color_pairs = [('Payment failed from bank','gray'),
 ('Insufficient funds in customer account. Please add more funds and try the transaction again.','tomato'),
  ('No response from your bank','skyblue'),
   ('Password locked due to multiple incorrect attempts. Choose Forgot Password to unlock.','green'),
    ('Payment failed from bank','gray'),
     ('Payment overdue','purple'),
      ('Transaction temporarily limited','blue'),
       ('Need verify your account to continue','peru')]

plt.figure(figsize=(15,4))
for error, color in error_color_pairs:
  df_err_line = df_error_0[df_error_0['description']==error]
  plt.plot(df_err_line['year_month'],
           df_err_line['n_ords'],
           label=error,
           marker='o',
           color=color,
           linewidth=2,
           markersize=2)

plt.title('Total Tickets of error group by months (Failed)')
plt.xlabel('month')
plt.ylabel('Number of Tickets')
plt.legend(loc='upper right',bbox_to_anchor=(1.15,1))
plt.xticks(rotation=90)
plt.show()

"""Notes:
-  Errors in this group match overall customer errors
- Reasons for failure and no retry:
> - Bank issues beyond their control
> - Account verification failure (fraud suspicion or upgrade rejection)

# **4. Insights and Recommendations**

**You can click this link to have a quick view of Insights & Recommendation**

**Thank you for taking the time to read this analysis. I appreciate your interest and welcome any feedback**
> **Nguyễn Thùy Linh**
>**ngthuylinh3003@gmail.com**
"""